#!/usr/bin/env python

import os
import sys

COMMON_LABEL = 'music'
GOOD_LABEL = 'good-music'
BAD_LABEL = 'bad-music'
THRESHOLD = 1.0
SIGNATURE = 'robot+better@tmradio.net'

if __name__ == '__main__':
    if not os.path.abspath(sys.argv[0]).startswith('/usr'):
        src_dir = os.path.abspath(os.path.join(os.path.dirname(sys.argv[0]), '..'))
        sys.path.insert(0, src_dir)

    import ardj
    a = ardj.Open()
    cur = a.database.cursor()
    cur.execute('DELETE FROM labels WHERE label = ?', (GOOD_LABEL, ))
    cur.execute('INSERT INTO labels (track_id, label, email) SELECT id, ?, ? FROM tracks WHERE id IN (SELECT track_id FROM labels WHERE label = ?) AND `weight` > ?', (GOOD_LABEL, SIGNATURE, COMMON_LABEL, THRESHOLD, ))
    cur.execute('INSERT INTO labels (track_id, label, email) SELECT id, ?, ? FROM tracks WHERE id IN (SELECT track_id FROM labels WHERE label = ?) AND `weight` <= ?', (BAD_LABEL, SIGNATURE, COMMON_LABEL, THRESHOLD, ))
    a.database.commit()
