#!/usr/bin/env python
# vim: set fileencoding=utf-8:

import mutagen
import os
import shutil
import subprocess
import sys
import tempfile
import traceback

import ardj.settings

DEFAULT_URL = 'http://broadcast.echo.msk.ru:9000/content/current.mp3'
DEFAULT_OUT = '/tmp/ardj-news.ogg'

def fetch_news():
    track_length = 0
    output_fn = tempfile.mkstemp(suffix='.ogg')[1]
    cmd = u"gst-launch-0.10 -q souphttpsrc location=\"%s\" ! decodebin ! audioconvert ! vorbisenc quality=0.5 ! oggmux ! filesink location=\"%s\"" % (ardj.settings.get('news/url', DEFAULT_URL), output_fn)

    from ardj import Open
    ardj = Open()

    try:
        subprocess.Popen(cmd.split(' ')).wait()
        if os.stat(output_fn).st_size:
            subprocess.Popen(['vorbisgain', '-f', '-q', output_fn]).wait()

            target_fn = ardj.settings.getpath('news/out', DEFAULT_OUT)
            if os.path.exists(target_fn):
                os.unlink(target_fn)
            os.chmod(output_fn, 0664)
            shutil.move(output_fn, target_fn)

            tags = mutagen.File(target_fn)
            if tags:
                track_length = int(tags.info.length)
    except Exception, e:
        print >>sys.stderr, 'Could not fetch news: %s' % e
        traceback.print_exc(e)

    track_id = int(ardj.settings.get('news/track_id', '0')
    if track_id:
        ardj.database.cursor().execute('UPDATE tracks SET length = ? WHERE id = ?', (track_length, track_id, ))
        ardj.queue_track(track_id)
        if ardj.settings.get('queue') == 'yes':
            ardj.queue_track(track_id)
        ardj.database.commit()

    return track_length != 0


if __name__ == '__main__':
    fetch_news()
