#!/bin/sh
if [ -z "$PAM_USER" ]; then
	echo "ERROR: set the PAM_USER envar."
	exit 1
fi

if [ -z "$PAM_TYPE" ]; then
	echo "ERROR: this script should be called by pam, the PAM_TYPE envar must contain 'close_session'."
	exit 1
fi

INCOMING_DIR=/home/$PAM_USER/incoming
RADIO_USER=radio

test -f /etc/ardj && . /etc/ardj

if [ -d "$INCOMING_DIR" -a "$PAM_TYPE" = "close_session" ]; then
	chmod -R g+w $INCOMING_DIR
	su -c "ardj db import" $RADIO_USER
fi
