#!/usr/bin/env python
# vim: set fileencoding=utf-8:

import os
import sys
import time

import ardj.settings
import ardj.twitter

if __name__ == '__main__':
    src = ardj.settings.getpath('stream/dump')
    dst = time.strftime(ardj.settings.getpath('stream/dump_rename_to'))

    if not os.path.exists(src):
        print >>sys.stderr, 'False start: %s not found.' % src
        sys.exit(1)

    os.rename(src, dst)

    ardj.twitter.twit(ardj.settings.get('stream/twit_begin'))
