#!/usr/bin/env python
# vim: set fileencoding=utf-8:

import os
import sys

if __name__ == '__main__':
    if not os.path.abspath(sys.argv[0]).startswith('/usr'):
        src_dir = os.path.abspath(os.path.join(os.path.dirname(sys.argv[0]), '..'))
        sys.path.insert(0, src_dir)

    if len(sys.argv) < 2:
        print >>sys.stderr, 'Usage: %s "message"' % sys.argv[0]
        sys.exit(1)

    from ardj import Open
    ardj = Open()
    print ardj.twit(sys.argv[1])
