#!/usr/bin/env python
# vim: set fileencoding=utf-8:

import os
import sys

if __name__ == '__main__':
    if not os.path.abspath(sys.argv[0]).startswith('/usr'):
        src_dir = os.path.abspath(os.path.join(os.path.dirname(sys.argv[0]), '..'))
        sys.path.insert(0, src_dir)

    if len(sys.argv) < 2:
        print >>sys.stderr, 'Usage: %s "message"' % sys.argv[0]
        sys.exit(1)

    from ardj import Open
    ardj = Open()

    if '-replies' in sys.argv:
        track_id = ardj.config.get('twitter/reply_track_id', fail=True)
        messages = [(s.user.screen_name, s.text) for s in sorted(ardj.twit_replies(), key=lambda s: s.created_at_in_seconds, reverse=True) if s.text.startswith('@tmradio ')]
        if messages:
            nick, text = messages[0]
            text = u' '.join(text.split(u' ')[1:])
            ardj.say_to_track(text, track_id, track_artist='@' + nick, queue=True)
    else:
        print ardj.twit(sys.argv[1])
