#!/usr/bin/env python

import glob
import os
import re
import shutil
import subprocess
import sys
import urllib2


URL_SOURCE = "http://echo.msk.ru/sounds/news.html"


def fetch_news(folder, target):
    page = urllib2.urlopen(URL_SOURCE).read()
    for url in re.findall("http://.+\.mp3", page):
        if not url.endswith(".mp3"):
            continue
        episode_name = url.split("/")[-1]
        episode_file = os.path.join(folder, episode_name)
        if not os.path.exists(episode_file):
            print "Downloading %s" % url
            data = urllib2.urlopen(url).read()
            file(episode_file, "wb").write(data)

    files = glob.glob(os.path.join(folder, "*.mp3"))
    if not files:
        return

    last_file = sorted(files)[-1]

    temp_file = last_file + ".ogg"
    file(temp_file, "wb").write(file(last_file, "rb").read())

    subprocess.Popen(["sox", last_file, "-r", "44100", "-c", "2", temp_file]).wait()
    subprocess.Popen(["vorbisgain", "-q", temp_file]).wait()

    if os.path.exists(target):
        os.unlink(target)
    shutil.move(temp_file, target)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print >> sys.stderr, "Usage: %s cache_folder target_file" % sys.argv[0]
        exit(1)

    if not sys.argv[2].endswith(".ogg"):
        print >> sys.stderr, "Target file must be OGG/Vorbis."
        exit(1)

    fetch_news(sys.argv[1], sys.argv[2])
