.TH "ardj" "1" "October 2011" "ardj" "an artificial DJ"
.SH NAME
ardj \- an internet radio playlist manager

.SH SYNOPSIS
.B ardj
.IR command

.nh
.SH DESCRIPTION
ardj is a collection of tools that can be used to run a full featured internet
radio station.  It uses an SQLite database to store the runtime data, a tiny
web server to access it, an XMPP (Jabber) bot for runtime management and to
interact with the audience, and a plugin which feeds ices0.

The complete documentation is available at <http://ardj.googlecode.com>.

.SH CONFIGURATION
There is one configuration wile which contains all settings.  This file is
named /etc/ardj.yaml, if you're installing system wide, or
~/.config/ardj/ardj.yaml if you're testing locally.

There is an example fully documented config file in the examples folder.

.SH FILES
.TP
.I /etc/ardj.yaml
The normal configuration file.
.TP
.I $HOME/.config/ardj/ardj.yaml
Your local config file, has higher priority. Can be used for testing.
.TP
.I /var/lib/ardj/music/playlists.yaml
The default playlists file.

.SH AUTHORS
ardj was originally written and is currently developed by Justin Forest <hex@umonkey.net>.
