#!/bin/sh
DIR="$1"

# echo "Calculating ReplayGain ..."
which mp3gain >/dev/null && find "$DIR" -iname '*.mp3' -exec nice -n 20 mp3gain -q -s i \{\} \; >/dev/null
which vorbisgain >/dev/null && find "$DIR" -iname '*.ogg' -exec nice -n 20 vorbisgain -f -q \{\} \;

# echo "Importing files in $DIR ..."
which ardj >/dev/null && find "$DIR" -iregex '.*\.\(mp3\|ogg\)$' -exec ardj --tags=incoming --delete --add \{\} \;
