#!/usr/bin/env python
# vim: set fileencoding=utf-8:
#
# Details:
# http://code.google.com/p/ardj/wiki/Statistics

import csv
import sys

def merge(filenames):
    data = {}
    for filename in filenames:
        r = csv.reader(open(filename, 'rb'))
        for row in r:
            if len(row) < 4:
                continue
            artist = row[2].strip().decode('utf-8')
            title = row[3].strip().decode('utf-8')
            count = int(row[4])
            if not data.has_key(artist):
                data[artist] = {}
            if not data[artist].has_key(title):
                data[artist][title] = 0
            data[artist][title] += count
    return data

def format_data(data):
    f = csv.writer(sys.stdout)
    for artist in sorted(data.keys()):
        tracks = data[artist]
        for title in sorted(tracks.keys()):
            f.writerow([artist.encode('utf-8'), title.encode('utf-8'), tracks[title]])

if __name__ == '__main__':
    format_data(merge(sys.argv[1:]))
